# Generated by Django 4.2 on 2023-08-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='current_revision',
            field=models.OneToOneField(blank=True, help_text='The revision of this attachment currently in use (on all articles using the attachment)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_set', to='attachments.attachmentrevision', verbose_name='current revision'),
        ),
        migrations.AlterField(
            model_name='attachmentrevision',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.attachment'),
        ),
        migrations.AlterField(
            model_name='attachmentrevision',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachments.attachmentrevision'),
        ),
    ]
