[tox]
envlist = py{312}-django{42, 52}

[testenv]
deps = 
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    -r{toxinidir}/requirements/test.txt
changedir = {toxinidir}/testproject/
commands = 
    pytest --cov wiki --cov django_notify
