# Generated by Django 4.2 on 2023-08-05 16:35

from django.db import migrations, models
import wiki.plugins.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerevision',
            name='image',
            field=models.ImageField(
                blank=True, height_field='height', max_length=2000,
                null=True, upload_to=wiki.plugins.images.models.upload_path,
                width_field='width'
            ),
        ),
    ]
